name: build-go-binary

on:
  release:
    types: [created] # 表示在创建新的 Release 时触发

jobs:
  build-go-binary:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows] # 需要打包的系统
        goarch: [amd64, arm64] # 需要打包的架构
    steps:
      - name: Node Setup
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Pnpm Setup
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/checkout@v3

      - name: build front src
        run: |
          git clone https://github.com/jinzhongjia/newMovie.git --depth=1 src/front
          cd src/front;pnpm install;pnpm build
          cd ..
          cd ..
          cp -r src/front/dist/ dist/front
          git clone https://github.com/jinzhongjia/newMovieAdmin.git --depth=1 src/admin
          cd src/admin;pnpm install;pnpm build
          cd ..
          cd ..
          cp -r src/admin/dist/ dist/admin

      - name: build
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o movie-${{ github.ref }}
          CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o movie-${{ github.ref }}.exe

      - name: Upload assets
        uses: softprops/action-gh-release@v1
        with:
          files:
            movie-${{ github.ref }}
            movie-${{ github.ref }}.exe
          prerelease: false
